name: the-windup-bird

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - uses: actions/setup-node@v2
      #   with:
      #     node-version: '17.x'
      #     registry-url: 'https://npm.pkg.github.com'
      # - run: npm ci
      # - run: npm publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Build Docker Image
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1.2.0
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.6.0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: Devops-as-a-Service-Project
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/${{ github.repository }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=sha
      - name: Build and push
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          # tags: ghcr.io/${{ github.repository }}